env:
  - VER=linux-win

matrix:
  include:
    - language: go
      go: "1.10.2"
      env: VER=linux-win
      before_install:
        - go get github.com/luca-moser/caddy-iri-attach
        - cd ../.. && mv luca-moser mholt
      install:
        - cd mholt/caddy     
        - go get -v ./...
        - caddy
        - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go run build.go
        - md5sum caddy
        - ls
      after_script:
        - cd .. #change back to root
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t lucamoser/caddy-iri:latest .
        - docker push lucamoser/caddy-iri:latest
