env:
  - VER=linux-win
  
matrix:
  include:
    - language: go
      go: "1.10.2"
      env: VER=linux-win
      install:
        - ls      
        - go get github.com/luca-moser/caddy-iri-attach
        - go get github.com/caddyserver/builds
        - mkdir -p /home/travis/gopath/src/github.com/mholt/caddy
        - rm -R /home/travis/gopath/src/github.com/mholt/caddy/*
        - cp -rp /home/travis/gopath/src/github.com/luca-moser/caddy-iri/* /home/travis/gopath/src/github.com/mholt/caddy
        - cd /home/travis/gopath/src/github.com/mholt/caddy
        - ls
        - cd caddy        
        - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go run build.go
        - md5sum caddy
        - cd .. 
        - ls
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t $DOCKER_REPO:latest .
        - docker push $DOCKER_REPO:latest
