env:
  - VER=linux-win
  
matrix:
  include:
    - language: go
      go: "1.10.2"
      env: VER=linux-win
      before_install:
        - ls      
        - go get github.com/luca-moser/caddy-iri-attach
        - go get github.com/caddyserver/builds
        - ls              
        - cd ../.. && mv luca-moser mholt
      install:
        - cd mholt/caddy     
        - cd caddy
        - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go run build.go
        - md5sum caddy
        - cd .. 
        - ls
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t $DOCKER_REPO:latest .
        - docker push $DOCKER_REPO:latest
