env:
  - VER=linux-win

matrix:
  include:
    - language: go
      go: "1.10.2"
      install:
        - ls      
        - go get github.com/luca-moser/caddy-iri-attach
        - go get github.com/captncraig/caddy-realip
        - go get github.com/kodnaplakal/caddy-geoip
        - go get github.com/xuqingfeng/caddy-rate-limit
        - go get github.com/caddyserver/builds
        - mkdir -p /home/travis/gopath/src/github.com/mholt/caddy
        - rm -R /home/travis/gopath/src/github.com/mholt/caddy/*
        - cp -rp /home/travis/gopath/src/github.com/luca-moser/caddy-iri/* /home/travis/gopath/src/github.com/mholt/caddy
        - cd /home/travis/gopath/src/github.com/mholt/caddy
        - ls
      script:        
        - cd caddy        
        - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go run build.go
        - md5sum caddy
        - cd ..
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t $DOCKER_REPO:latest .
        - docker push $DOCKER_REPO:latest

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - caddy/caddy
    skip_cleanup: true
    on:
      all_branches: true