env:
  - VER=linux-win

matrix:
  include:
    - language: go
      go: "1.10.2"
      env: VER=linux-win
      before_install:
        - go get github.com/luca-moser/caddy-iri-attach
      script:
        - mv $HOME/gopath/src/github.com/luca-moser $HOME/gopath/src/github.com/mholt
        - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -o caddy-iri-$TRAVIS_TAG-linux64
        - md5sum caddy-iri-$TRAVIS_TAG-linux64
        - ls
      after_script:
        - cd .. #change back to root
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t lucamoser/caddy-iri:latest .
        - docker push lucamoser/caddy-iri:latest